In [61]:

import pandas as pd
import numpy as np; np.random.seed(1)  # fix a seed for reproducible random sampling
import matplotlib.pyplot as plt
import scipy.special
import itertools

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.naive_bayes import GaussianNB
clf= GaussianNB()

In [62]:
df = pd.read_csv('corpus/federalist-papersNew2.csv', index_col=0)
words_of_interest = ['upon', 'to', 'would','while','up']
df[words_of_interest].head()

   upon  to  would  while  up
1     6  72      2      0   0
2     1  53      5      1   0
3     0  56      2      0   0
4     0  51     17      0   0
5     0  45     37      0   0

In [63]:
fed = disputed_essays = df[df['AUTHOR'] == 'Hamilton OR Madison'].index
assert len(disputed_essays) == 12  # there are twelve disputed essays
# numbers widely used to identify the essays
assert set(disputed_essays) == {49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 62, 63}

In [64]:
fed = df_known = df.loc[df['AUTHOR'].isin(('Hamilton', 'Madison'))]
print(df_known['AUTHOR'].value_counts())
fed

Hamilton    51
Madison     14
Name: AUTHOR, dtype: int64

,000,1,10,100,104,105,109,11,114,115,...,young,your,yourself,yourselves,zaleucus,zeal,zealand,zealous,zelden,AUTHOR
1,0,2,0,0,0,0,0,0,0,0,...,0,10,0,0,0,3,0,0,0,Hamilton
6,0,2,2,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,Hamilton
7,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,Hamilton
8,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hamilton
9,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hamilton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hamilton
82,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hamilton
83,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hamilton
84,0,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,2,0,0,0,Hamilton
85,0,2,0,0,0,0,0,0,0,0,...,0,4,0,0,0,1,0,2,0,Hamilton

In [65]:
df_known.groupby('AUTHOR')[words_of_interest].head()

    upon   to  would  while  up
1      6   72      2      0   0
6      4   58      6      0   0
7     11   82     51      0   1
8      3   80     27      0   3
9      4   71      8      1   0
10     0  100      6      0   1
14     0   72      5      0   0
37     1   85      7      0   0
38     4  117     15      0   0
39     0   91      8      0   0

In [66]:
known_pap=fed[['upon','would','to','while','up','AUTHOR']]
#known_pap.head()

#known_pap=known_pap.groupby('AUTHOR').sum()
#known_pap['Subset_length'] = known_pap.sum(axis=1)
known_pap['Author_Group']=le.fit_transform(known_pap['AUTHOR'])
known_pap=known_pap.drop('AUTHOR', axis=1)
known_pap


upon_prob_ham=known_pap[ known_pap['Author_Group']==0]
upon_prob=upon_prob_ham['upon'].sum()
print(upon_prob)
#total_sum_ham=
deno_ham=np.sum(upon_prob_ham.sum(),axis=0)
deno_ham
#total_upon_prob_ham=

374

<ipython-input-66-a4121feae832>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  known_pap['Author_Group']=le.fit_transform(known_pap['AUTHOR'])

5957

In [67]:
disputed_essays = df[df['AUTHOR'] == 'Hamilton OR Madison']
disputed_essays.head()

,000,1,10,100,104,105,109,11,114,115,...,young,your,yourself,yourselves,zaleucus,zeal,zealand,zealous,zelden,AUTHOR
49,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hamilton OR Madison
50,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hamilton OR Madison
51,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Hamilton OR Madison
52,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,Hamilton OR Madison
53,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,Hamilton OR Madison

In [68]:
disp_essays=disputed_essays[['upon','would','to','while','up','AUTHOR']]
disp_essays

    upon  would  to  while  up               AUTHOR
49     0     22  58      0   0  Hamilton OR Madison
50     1     11  28      0   0  Hamilton OR Madison
51     0      9  50      0   0  Hamilton OR Madison
52     0      8  72      0   0  Hamilton OR Madison
53     0      6  73      0   0  Hamilton OR Madison
54     2      6  61      0   0  Hamilton OR Madison
55     0     10  78      0   1  Hamilton OR Madison
56     0      4  39      0   0  Hamilton OR Madison
57     0      6  74      0   0  Hamilton OR Madison
58     0     12  61      0   0  Hamilton OR Madison
62     0      5  82      0   0  Hamilton OR Madison
63     0     11  88      0   2  Hamilton OR Madison

In [69]:
#known_pap['Author_Group']=le.fit_transform(known_pap['AUTHOR'])
#known_pap=known_pap.drop('AUTHOR', axis=1)
known_pap.head()

   upon  would  to  while  up  Author_Group
1     6      2  72      0   0             0
6     4      6  58      0   0             0
7    11     51  82      0   1             0
8     3     27  80      0   3             0
9     4      8  71      1   0             0

In [70]:
disp_essay_test=disp_essays.drop('AUTHOR',axis=1)
disputed_essays = df[df['AUTHOR'] == 'Hamilton OR Madison']
#prioir_ham=len(known_pap[known_pap['Author_Group']==0])/len(known_pap)
#prioir_mad=len(known_pap[known_pap['Author_Group']==1])/len(known_pap)
#print(prioir_ham,prioir_mad)
#print(disp_essay_test)

print(disp_essay_test.iloc[0].loc['upon'])



disp_essay_test.iloc[0]

0

upon      0
would    22
to       58
while     0
up        0
Name: 49, dtype: int64

Naive Bayes Model with different attributes:

1. Calculate prior for all catergories of the Output
2. Calculate the conditional probability for each category for each attribute
3. Sumthe log of conditional probability and prior for each catergory
4. Obtain the argmax for the 
5. Repeat steps for each test sample.

In [71]:
def prior(df,Y):
    classes= df[Y].unique()
    prior=[]
    for category in classes:
        prior.append(len(df[df[Y]==category])/len(df))
        #print(prior)
    return prior
def conditional_probability(df,feat_name,feat_val,Y,label):
    feat=list(df.columns)
    df=df[df[Y]==label]
    alpha=1
    num= df[feat_name].sum()+1
    dem=np.sum(df.sum(),axis=0)+feat_val
    print('prob= ',num/dem)
    return np.log(num/dem)

def naive_bayes(df,X_test,Category):
    features= list(df.columns)[:-1]
    classes=df[Category].unique()
    priors=[]
    priors=prior(df,Category)
    print(priors)
    Y_pred=[]
    
    for x in range(len(X_test)):
        print('value x=  ',x)
       
        classes=list(df[Category].unique())
        posteriors=[]
        
        for i in range((len(classes))):
            posterior=0
            
            cond_prob=0
            for j in range(len(features)):
                count=X_test.iloc[x].loc[features[j]]
                print(cond_prob,'features :=',features[j], x,count)
                cond_prob+=count*conditional_probability(df,features[j],len(features),Category,classes[i])
            posterior=np.log(priors[i])+cond_prob
            posteriors.append(posterior)
            print('posteriors',posteriors)
        Y_pred.append(np.argmax(posteriors))
    return np.array(Y_pred)


df=known_pap    
X_test=disp_essay_test
naive_bayes(df,X_test,Category='Author_Group')
#X_train=known_pap[['upon','would','to','while','up']]
#Y_train=known_pap['Author_Group']
#fit(X_train,Y_train)

[0.7846153846153846, 0.2153846153846154]
value x=   0
0 features := upon 0 0
prob=  0.06289835625628984
0.0 features := would 0 22
prob=  0.1559879235155988
-40.875487137995734 features := to 0 58
prob=  0.7690372358269038
-56.10720873174792 features := while 0 0
prob=  0.006205971150620597
-56.10720873174792 features := up 0 0
prob=  0.005870513250587051
posteriors [-56.34977036891923]
0 features := upon 0 0
prob=  0.005521048999309869
0.0 features := would 0 22
prob=  0.11042097998619738
-48.476012795910826 features := to 0 58
prob=  0.8709454796411318
-56.490214950643214 features := while 0 0
prob=  0.0006901311249137336
-56.490214950643214 features := up 0 0
prob=  0.0027605244996549345
posteriors [-56.34977036891923, -58.02554489092359]
value x=   1
0 features := upon 1 1
prob=  0.06289835625628984
-2.766235248267606 features := would 1 11
prob=  0.1559879235155988
-23.203978817265472 features := to 1 28
prob=  0.7690372358269038
-30.557223724594113 features := while 1 0
prob=  0.006205971150620597
-30.557223724594113 features := up 1 0
prob=  0.005870513250587051
posteriors [-30.799785361765423]
0 features := upon 1 1
prob=  0.005521048999309869
-5.199187400640846 features := would 1 11
prob=  0.11042097998619738
-29.437193798596258 features := to 1 28
prob=  0.8709454796411318
-33.30611897674293 features := while 1 0
prob=  0.0006901311249137336
-33.30611897674293 features := up 1 0
prob=  0.0027605244996549345
posteriors [-30.799785361765423, -34.84144891702331]
value x=   2
0 features := upon 2 0
prob=  0.06289835625628984
0.0 features := would 2 9
prob=  0.1559879235155988
-16.721790192816435 features := to 2 50
prob=  0.7690372358269038
-29.85258467018901 features := while 2 0
prob=  0.006205971150620597
-29.85258467018901 features := up 2 0
prob=  0.005870513250587051
posteriors [-30.09514630736032]
0 features := upon 2 0
prob=  0.005521048999309869
0.0 features := would 2 9
prob=  0.11042097998619738
-19.8310961437817 features := to 2 50
prob=  0.8709454796411318
-26.7398911047579 features := while 2 0
prob=  0.0006901311249137336
-26.7398911047579 features := up 2 0
prob=  0.0027605244996549345
posteriors [-30.09514630736032, -28.275221045038275]
value x=   3
0 features := upon 3 0
prob=  0.06289835625628984
0.0 features := would 3 8
prob=  0.1559879235155988
-14.863813504725721 features := to 3 72
prob=  0.7690372358269038
-33.772157552142225 features := while 3 0
prob=  0.006205971150620597
-33.772157552142225 features := up 3 0
prob=  0.005870513250587051
posteriors [-34.01471918931354]
0 features := upon 3 0
prob=  0.005521048999309869
0.0 features := would 3 8
prob=  0.11042097998619738
-17.627641016694845 features := to 3 72
prob=  0.8709454796411318
-27.576305760500567 features := while 3 0
prob=  0.0006901311249137336
-27.576305760500567 features := up 3 0
prob=  0.0027605244996549345
posteriors [-34.01471918931354, -29.111635700780944]
value x=   4
0 features := upon 4 0
prob=  0.06289835625628984
0.0 features := would 4 6
prob=  0.1559879235155988
-11.147860128544291 features := to 4 73
prob=  0.7690372358269038
-30.31882006550825 features := while 4 0
prob=  0.006205971150620597
-30.31882006550825 features := up 4 0
prob=  0.005870513250587051
posteriors [-30.561381702679558]
0 features := upon 4 0
prob=  0.005521048999309869
0.0 features := would 4 6
prob=  0.11042097998619738
-13.220730762521134 features := to 4 73
prob=  0.8709454796411318
-23.307571405546383 features := while 4 0
prob=  0.0006901311249137336
-23.307571405546383 features := up 4 0
prob=  0.0027605244996549345
posteriors [-30.561381702679558, -24.84290134582676]
value x=   5
0 features := upon 5 2
prob=  0.06289835625628984
-5.532470496535212 features := would 5 6
prob=  0.1559879235155988
-16.680330625079502 features := to 5 61
prob=  0.7690372358269038
-32.69989988747405 features := while 5 0
prob=  0.006205971150620597
-32.69989988747405 features := up 5 0
prob=  0.005870513250587051
posteriors [-32.94246152464536]
0 features := upon 5 2
prob=  0.005521048999309869
-10.398374801281692 features := would 5 6
prob=  0.11042097998619738
-23.619105563802826 features := to 5 61
prob=  0.8709454796411318
-32.047835416193784 features := while 5 0
prob=  0.0006901311249137336
-32.047835416193784 features := up 5 0
prob=  0.0027605244996549345
posteriors [-32.94246152464536, -33.58316535647416]
value x=   6
0 features := upon 6 0
prob=  0.06289835625628984
0.0 features := would 6 10
prob=  0.1559879235155988
-18.57976688090715 features := to 6 78
prob=  0.7690372358269038
-39.06380626560836 features := while 6 0
prob=  0.006205971150620597
-39.06380626560836 features := up 6 1
prob=  0.005870513250587051
posteriors [-44.44418111552828]
0 features := upon 6 0
prob=  0.005521048999309869
0.0 features := would 6 10
prob=  0.11042097998619738
-22.034551270868555 features := to 6 78
prob=  0.8709454796411318
-32.812271409991425 features := while 6 0
prob=  0.0006901311249137336
-32.812271409991425 features := up 6 1
prob=  0.0027605244996549345
posteriors [-44.44418111552828, -40.239935931472594]
value x=   7
0 features := upon 7 0
prob=  0.06289835625628984
0.0 features := would 7 4
prob=  0.1559879235155988
-7.431906752362861 features := to 7 39
prob=  0.7690372358269038
-17.67392644471347 features := while 7 0
prob=  0.006205971150620597
-17.67392644471347 features := up 7 0
prob=  0.005870513250587051
posteriors [-17.91648808188478]
0 features := upon 7 0
prob=  0.005521048999309869
0.0 features := would 7 4
prob=  0.11042097998619738
-8.813820508347423 features := to 7 39
prob=  0.8709454796411318
-14.202680577908858 features := while 7 0
prob=  0.0006901311249137336
-14.202680577908858 features := up 7 0
prob=  0.0027605244996549345
posteriors [-17.91648808188478, -15.738010518189236]
value x=   8
0 features := upon 8 0
prob=  0.06289835625628984
0.0 features := would 8 6
prob=  0.1559879235155988
-11.147860128544291 features := to 8 74
prob=  0.7690372358269038
-30.5814359550557 features := while 8 0
prob=  0.006205971150620597
-30.5814359550557 features := up 8 0
prob=  0.005870513250587051
posteriors [-30.82399759222701]
0 features := upon 8 0
prob=  0.005521048999309869
0.0 features := would 8 6
prob=  0.11042097998619738
-13.220730762521134 features := to 8 74
prob=  0.8709454796411318
-23.445747304765906 features := while 8 0
prob=  0.0006901311249137336
-23.445747304765906 features := up 8 0
prob=  0.0027605244996549345
posteriors [-30.82399759222701, -24.981077245046283]
value x=   9
0 features := upon 9 0
prob=  0.06289835625628984
0.0 features := would 9 12
prob=  0.1559879235155988
-22.295720257088583 features := to 9 61
prob=  0.7690372358269038
-38.31528951948312 features := while 9 0
prob=  0.006205971150620597
-38.31528951948312 features := up 9 0
prob=  0.005870513250587051
posteriors [-38.557851156654436]
0 features := upon 9 0
prob=  0.005521048999309869
0.0 features := would 9 12
prob=  0.11042097998619738
-26.441461525042268 features := to 9 61
prob=  0.8709454796411318
-34.87019137743323 features := while 9 0
prob=  0.0006901311249137336
-34.87019137743323 features := up 9 0
prob=  0.0027605244996549345
posteriors [-38.557851156654436, -36.40552131771361]
value x=   10
0 features := upon 10 0
prob=  0.06289835625628984
0.0 features := would 10 5
prob=  0.1559879235155988
-9.289883440453576 features := to 10 82
prob=  0.7690372358269038
-30.824386383344596 features := while 10 0
prob=  0.006205971150620597
-30.824386383344596 features := up 10 0
prob=  0.005870513250587051
posteriors [-31.066948020515905]
0 features := upon 10 0
prob=  0.005521048999309869
0.0 features := would 10 5
prob=  0.11042097998619738
-11.017275635434277 features := to 10 82
prob=  0.8709454796411318
-22.34769937143524 features := while 10 0
prob=  0.0006901311249137336
-22.34769937143524 features := up 10 0
prob=  0.0027605244996549345
posteriors [-31.066948020515905, -23.883029311715617]
value x=   11
0 features := upon 11 0
prob=  0.06289835625628984
0.0 features := would 11 11
prob=  0.1559879235155988
-20.437743568997867 features := to 11 88
prob=  0.7690372358269038
-43.5479418491736 features := while 11 0
prob=  0.006205971150620597
-43.5479418491736 features := up 11 2
prob=  0.005870513250587051
posteriors [-54.06612991184212]
0 features := upon 11 0
prob=  0.005521048999309869
0.0 features := would 11 11
prob=  0.11042097998619738
-24.238006397955413 features := to 11 88
prob=  0.8709454796411318
-36.397485529273524 features := while 11 0
prob=  0.0006901311249137336
-36.397485529273524 features := up 11 2
prob=  0.0027605244996549345
posteriors [-54.06612991184212, -49.717484631955486]

array([0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1], dtype=int64)

In [72]:
X_train=known_pap[['upon','would','to','while','up']]
Y_train=known_pap['Author_Group']
X_test=disp_essay_
clf.fit(X_train,Y_train)
y_pred=clf.predict(X_test)
y_pred

ValueError: could not convert string to float: 'Hamilton OR Madison'

In [81]:

Y_train=known_pap['Author_Group']
Y_train.head()

1    0
6    0
7    0
8    0
9    0
Name: Author_Group, dtype: int32

In [79]:
Y_train.unique()

array([0, 1])

In [82]:
Y_train.value_counts

<bound method IndexOpsMixin.value_counts of 1     0
6     0
7     0
8     0
9     0
     ..
81    0
82    0
83    0
84    0
85    0
Name: Author_Group, Length: 65, dtype: int32>

In [87]:

#Jen-testing

def fit(X,Y):
    n_sample,n_feature=X.shape
    classes= np.unique(Y)
    n_classes=len(classes)
    #for c in np.unique(Y):
    mean_all=np.zeros((n_classes,n_feature),dtype=np.float64)    
    var_all=np.zeros((n_classes,n_feature),dtype=np.float64)    
    priors_all=np.zeros(n_classes,dtype=np.float64)
    
    for c in classes:
        X_c=X[c==Y]
        mean_all[c,:]=X_c.mean(axis=0)
        var_all[c,:]=X_c.var(axis=0)
        priors_all[c]=X_C.shape[0]/float(n_sample)
   # return var_all[1,]
def predit(X_test):
    y_pred=np.zeros(len(X_test),dtype=np.float64)
    for x in X_test:
        posteriors=[]
        
        for index,col in enumerate(classes):
                prior=np.log(priors_all[index])
                class_conditional= np.sum(np.log(pdf(index,x)))
                posterior=prior+class_conditional
                posteriors.append(posterior)
        y_pred.append(np.argmax(posteriors))
    return y_pred

def pdf(index,x):
    mean= mean_all[index]
    var=var_all[index]